---
- name: include vars
  include_vars: vars.yml

- name: Add the user vagrant to the user's group 
  user:
    name: "{{ username }}"
    groups: microk8s
    append: yes

- name: Create a directory if it does not exist
  file:
    path: /home/"{{ username }}"/.kube
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0750'